"""initial migrations

Revision ID: 471831f5c4f1
Revises: 4917da928a79
Create Date: 2023-10-19 11:44:47.356148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471831f5c4f1'
down_revision = '4917da928a79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
