"""creat users table

Revision ID: 7a29870a3195
Revises: d0fd8e04165f
Create Date: 2023-11-20 14:52:58.642528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a29870a3195'
down_revision = 'd0fd8e04165f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
