"""creat users table

Revision ID: 8affa8eb94f6
Revises: 7a29870a3195
Create Date: 2023-11-20 14:53:40.353582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8affa8eb94f6'
down_revision = '7a29870a3195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
