"""add categoreis

Revision ID: d0fd8e04165f
Revises: f9e1cccbe381
Create Date: 2023-10-19 14:07:26.679213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fd8e04165f'
down_revision = 'f9e1cccbe381'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
